USE DATABASE DEMODATABASE;

CREATE OR REPLACE TABLE AM_BRILLIANT_BRITISH_CAR(
CAR_NO INT PRIMARY KEY,
InvoiceDate VARCHAR (15),
Make VARCHAR (20),
CountryName VARCHAR (20),
IsDealer VARCHAR (5),
SalePrice NUMBER (10,0),
CostPrice NUMBER (10,0),
TotalDiscount INTEGER,
DeliveryCharge INTEGER,
SpareParts INTEGER,
LaborCost INTEGER,
ClientName VARCHAR (50),
Model VARCHAR (20),
Color VARCHAR (30),
ReportingYear INTEGER,
ReportingMonth INTEGER,
Registeration_Date STRING,
VehicleType VARCHAR (20),
InvoiceNumber VARCHAR (40),
CountryISOCode VARCHAR (5),
OuterPostode VARCHAR (8),
Region VARCHAR (40)
);

DESC TABLE AM_BRILLIANT_BRITISH_CAR;

SELECT * FROM AM_BRILLIANT_BRITISH_CAR;
------------------------------------------------

/*WHEN THERE IS NO DATA, JUST COPYING THE STRUCTURE OF THE TABLE*/

CREATE OR REPLACE TABLE AM_BRILLIANT_CAR_COPY LIKE AM_BRILLIANT_BRITISH_CAR;


DESC TABLE AM_BRILLIANT_CAR_COPY;

CREATE OR REPLACE TABLE AM_BRILLIANT_CAR_COPY AS 
SELECT * FROM AM_BRILLIANT_BRITISH_CAR;

SELECT * FROM AM_BRILLIANT_CAR_COPY;


DESC TABLE AM_BRILLIANT_CAR_COPY;


SELECT RTRIM('125.26','5.26') AS STRING;




