USE DATABASE DEMODATABASE;

CREATE or replace table AM_CONSUMER_COMPLAINTS

(    DATE_RECEIVED STRING,
     PRODUCT_NAME VARCHAR2(50),
     SUB_PRODUCT VARCHAR2(100),
     ISSUE VARCHAR2(100),
     SUB_ISSUE VARCHAR2(100),
     CONSUMER_COMPLAINT_NARRATIVE string,
     Company_Public_Response STRING,
     Company VARCHAR(100),
     State_Name CHAR(4),
     Zip_Code string,
     Tags VARCHAR(40),
     Consumer_Consent_Provided CHAR(25),
     Submitted_via STRING,
     Date_Sent_to_Company STRING,
     Company_Response_to_Consumer VARCHAR(40),
     Timely_Response CHAR(4),
     CONSUMER_DISPUTED CHAR(4),
     COMPLAINT_ID NUMBER(12,0) NOT NULL PRIMARY KEY);
     
     
SELECT * FROM AM_CONSUMER_COMPLAINTS;

SELECT DISTINCT * FROM AM_CONSUMER_COMPLAINTS WHERE SUB_PRODUCT LIKE 'C%e' ;

SELECT DISTINCT * FROM AM_CONSUMER_COMPLAINTS WHERE SUBMITTED_VIA LIKE '_a%';

SELECT DISTINCT COMPANY FROM AM_CONSUMER_COMPLAINTS;

SELECT SUB_PRODUCT FROM AM_CONSUMER_COMPLAINTS;





SELECT DISTINCT PRODUCT_NAME * FROM AM_CONSUMER_COMPLAINTS;

CASE 
     WHEN PRODUCT_NAME IN ('Consumer Loan' , 'Student loan' , 'Payday loan') THEN 'LOAN'
     WHEN PRODUCT_NAME IN ('Bank account or service' , 'Mortgage' , 'Debt Collection' , '') THEN 'LOAN'


;


SELECT DATE_RECEIVED, PRODUCT_NAME ,SUB_PRODUCT,ISSUE,
        CASE WHEN SUBMITTED_VIA IN ('Referral','Postal Mail','Email') THEN 'Outbound'
             WHEN SUBMITTED_VIA IN ('Phone','Web') THEN 'Inbound'
             ELSE 'Electronics'
         END AS Submission_Type,
         
         COMPANY,STATE_NAME,ZIP_CODE
         
FROM AM_CONSUMER_COMPLAINTS;



select *, case
when SUBMITTED_VIA in ('Phone' ,'Web') then 'INBOard'
when SUBMITTED_VIA = 'Fax' then 'Electronic'
else 'outboard'
end as Submission_type
FROM AM_CONSUMER_COMPLAINTS;



select *,
    CASE 
        wHen Product_Name like '%loan%' or Product_Name like '%Loan%' then 'Loan type'--THIS U CAN AVOIUD 
        when Product_Name in ('Bank account or service','Mortgage','Debt collection', 
                              'Credit reporting','Money transfers') then 'service'
        else 'other'
        
    end as Finance_type 
    from AM_CONSUMER_COMPLAINTS;


SELECT *,
	CASE
	WHEN SUB_PRODUCT = 'I do not know' or SUB_PRODUCT is null THEN 'NA'
	WHEN lower(SUB_PRODUCT) LIKE '%loan' THEN 'LOAN'
	WHEN lower(SUB_PRODUCT) LIKE '%card' THEN 'CARD'
	WHEN lower(SUB_PRODUCT) LIKE '%mortage' THEN 'MORTGAGE'
	ELSE SUB_PRODUCT
    END AS SUB_PRODUCT_TYPE
FROM AM_CONSUMER_COMPLAINTS;



SELECT * FROM AM_CONSUMER_COMPLAINTS;


SELECT *,
case
    when lower(sub_product) like '%loan' then 'LOAN'
    when lower(sub_product) like '%card' then 'CARD'
    when lower(sub_product) like '%mortgage' then 'MORTAGE'
    when sub_product ='I do not know' or sub_product is NULL  then 'NA'
    else sub_product
    end as subproduct_type
    from AM_CONSUMER_COMPLAINTS;


SELECT DISTINCT SUBMITTED_VIA FROM AM_CONSUMER_COMPLAINTS;


SELECT *, 
CASE        
          WHEN SUBMITTED_VIA IN ('Web' , 'Email') THEN 'ELECTRONIC'
          WHEN SUBMITTED_VIA IN ('Fax' , 'Phone' , 'Postal mail') THEN 'PHYSICAL'

          ELSE 'OTHER'
          
          END AS SUBMISSION_TYPE
          
          FROM AM_CONSUMER_COMPLAINTS;

SELECT SUBMISSION_TYPE FROM AM_CONSUMER_COMPLAINTS;




SELECT * FROM AM_CONSUMER_COMPLAINTS;


CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY AS
SELECT * FROM AM_CONSUMER_COMPLAINTS;


SELECT * FROM AM_CONSUMER_COMPLAINTS_COPY;


CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY AS
SELECT CUST_ID, SUB_PRODUCT FROM AM_CONSUMER_COMPLAINTS;

--to get the code of the table

SELECT get_ddl('table' , 'table_name');


SELECT * FROM AM_CONSUMER_COMPLAINTS_COPY;



-- IT WILL WORK WHEN TABLE IS EMPTY
ALTER TABLE AM_CONSUMER_COMPLAINTS_COPY 
ADD COLUMN AGE INT PRIMARY KEY;



-- WHEN TABLE IS NOT EMPTY

-- CREATE A COLUMN WITH PK

ALTER TABLE AM_CONSUMER_COMPLAINTS_COPY
ADD PRIMARY KEY ;


CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY LIKE AM_CONSUMER_COMPLAINTS;

--
CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY AS
SELECT * FROM AM_CONSUMER_COMPLAINTS;


DESC TABLE AM_CONSUMER_COMPLAINTS;

DESC TABLE AM_CONSUMER_COMPLAINTS_COPY;
--------------------------------------
--WHEN THERE IS NO DATA IN THE TABLE

CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY LIKE AM_CONSUMER_COMPLAINTS;

ALTER TABLE AM_CONSUMER_COMPLAINTS_COPY
DROP PRIMARY KEY;


ALTER TABLE AM_CONSUMER_COMPLAINTS_COPY
ADD COLUMN SERIAL_NUMBER VARCHAR (10) PRIMARY KEY;
--------------------------------------------------

--NOW THERE IS DATA IN AM_CONSUMER_COMPLAINTS_COPY--



CREATE OR REPLACE TABLE AM_CONSUMER_COMPLAINTS_COPY AS
SELECT * FROM AM_CONSUMER_COMPLAINTS;

DESCRIBE TABLE AM_CONSUMER_COMPLAINTS;

DESCRIBE TABLE AM_CONSUMER_COMPLAINTS_COPY;

SELECT * FROM AM_CONSUMER_COMPLAINTS_COPY;




SELECT CONVERT_TIMEZONE('America/Los_Angeles' , CURRENT_TIMESTAMP) AS AMERICA_TIMEZONE;

SELECT CONVERT_TIMEZONE('Asia/Kolkata' , CURRENT_TIMESTAMP) AS INDIA_TIMEZONE;

SELECT DATE_TRUNC ('YEAR' , CURRENT_DATE);

SELECT DATE_TRUNC ('YEAR' , DATE('2022-12-16'));


SELECT DATE_TRUNC ('MONTH' , CURRENT_DATE);

SELECT DATE_TRUNC ('DAY' , CURRENT_DATE);

SELECT DATE_TRUNC ('WEEK' , CURRENT_DATE);

SELECT DATE_TRUNC ('WEEK' , TO_DATE('2022-11-09'));

SELECT WEEK(CURRENT_DATE);
SELECT DAY(CURRENT_DATE);
SELECT MONTH(CURRENT_DATE);
SELECT YEAR(CURRENT_DATE);


SELECT WEEK(TO_DATE('2022-12-01'));
SELECT DAY(TO_DATE('2022-12-01'));
SELECT MONTH(TO_DATE('2022-12-01'));
SELECT YEAR(TO_DATE('2022-12-01'));

SELECT WEEK(TO_DATE('2001-12-01'));

SELECT YEAR(CURRENT_TIMESTAMP()),
MONTH(CURRENT_TIMESTAMP()),
DAY(CURRENT_TIMESTAMP()),
HOUR(CURRENT_TIMESTAMP()),
MINUTE(CURRENT_TIMESTAMP());

--17th Dec

SELECT * FROM "DEMODATABASE"."PUBLIC"."AM_CONSUMER_COMPLAINTS";

--TAKE THIS AS A HINT
CREATE OR REPLACE VIEW AM_CONSUMER_COMPLAINTS_VIEW AS
SELECT *,CONCAT(ZIP_CODE,PRODUCT_NAME) AS PROD_CODE_DETAILS
FROM AM_CONSUMER_COMPLAINTS
WHERE SUB_ISSUE IS NOT NULL AND
WHERE CONSUMER_COMPLAINT_NARRATIVE IS NOT NULL AND
COMPANY_PUBLIC_RESPONSE;


SELECT * FROM AM_CONSUMER_COMPLAINTS;

DESCRIBE VIEW AJ_CONSUMER_COMPLAINTS_VIEW;

SELECT * FROM AJ_CONSUMER_COMPLAINTS_VIEW;

create or replace VIEW CUSTOM_CONSUMER_COMPLAINTS_VIEW AS 
SELECT *, CONCAT(STATE_NAME,'-',ZIP_CODE) AS STATE_ZIP_DETAILS
FROM AM_CONSUMER_COMPLAINTS
WHERE SUB_ISSUE IS NOT NULL AND CONSUMER_COMPLAINT_NARRATIVE IS NOT NULL
AND SUB_PRODUCT IS NOT NULL
AND COMPANY_PUBLIC_RESPONSE IS NOT NULL;


create or replace VIEW CUSTOM_CONSUMER_COMPLAINTS_VIEW AS 
SELECT *, CONCAT(STATE_NAME,'-',ZIP_CODE) AS STATE_ZIP_DETAILS
FROM AM_CONSUMER_COMPLAINTS
WHERE SUB_ISSUE IS NOT NULL AND CONSUMER_COMPLAINT_NARRATIVE IS NOT NULL
AND SUB_PRODUCT IS NOT NULL
AND COMPANY_PUBLIC_RESPONSE IS NOT NULL;

SELECT * FROM CUSTOM_CONSUMER_COMPLAINTS_VIEW;

CREATE OR REPLACE VIEW AM_CUSTOM_CONSUMER_COMPLAINTS_VIEW AS
SELECT *, CONCAT(STATE_NAME, '-', ZIP_CODE) AS ZIP_DETAILS
FROM AM_CONSUMER_COMPLAINTS
    WHERE SUB_ISSUE IS NOT NULL OR 
    CONSUMER_COMPLAINT_NARRATIVE IS NOT NULL OR
    COMPANY_PUBLIC_RESPONSE IS NOT NULL OR
    TAGS IS NOT NULL;

SELECT * FROM AM_CUSTOM_CONSUMER_COMPLAINTS_VIEW;

CREATE OR REPLACE VIEW AM_CUSTOM_CONSUMER_COMPLAINTS_VIEW AS
SELECT *, CONCAT(STATE_NAME, '-', ZIP_CODE) AS ZIP_DETAILS
FROM AM_CONSUMER_COMPLAINTS
    WHERE SUB_ISSUE IS NOT NULL AND 
    CONSUMER_COMPLAINT_NARRATIVE IS NOT NULL AND
    COMPANY_PUBLIC_RESPONSE IS NOT NULL AND
    TAGS IS NOT NULL;     
     