USE DEMODATABASE;


SELECT DATE_TRUNC('YEAR', CURRENT_DATE) AS CURRENT_YEAR;
SELECT YEAR(CURRENT_DATE) AS CURRENT_YEAR;

SELECT DATE_TRUNC('MONTH', CURRENT_DATE) AS CURRENT_MONTH;
SELECT MONTH(current_DATE) AS CURRENT_MONTH_NO;

SELECT DATE_TRUNC('DAY', CURRENT_DATE) AS CURRENT_DAY;
SELECT DAY(CURRENT_DATE) AS CURRENT_DAY_NO;

SELECT DATE_TRUNC('WEEK', CURRENT_DATE) AS CURRENT_WEEK_START_DATE;

SELECT DATE_TRUNC('WEEK', DATE('2023-02-21')) AS CURRENT_WEEK_START_DATE;
SELECT WEEK (DATE('2023-02-21')) AS CURRENT_WEEK_NO ;

SELECT DATE_TRUNC('DAY', TO_DATE('2023-02-19')) AS CURRENT_DAY; -- TO CONVERT DAY FROM ANY TIME IF THE DATA TYPE OF TIME GIVEN IS VARCHAR OR STRING.
                                                                   FORMAT OF THE DATE IN STRING OR VARCHAR SHOULD BE 'YYYY-MM-DD'.
SELECT DATE_TRUNC('DAY', DATE('2023-02-19')) AS CURRENT_DAY; -- LINE 18&19 ARE SAME

SELECT WEEK(CURRENT_DATE) AS WEEK_FROM_START_OF_THE_YEAR;
SELECT WEEK(DATE('2023-02-21')) AS WEEK_FROM_START_OF_THE_YEAR;
SELECT MONTH(CURRENT_DATE) AS MNTH_FROM_START_OF_THE_YEAR;
SELECT MONTH(DATE('2023-02-21')) AS MONTH_FROM_START_OF_THE_YEAR;
SELECT DAY(CURRENT_DATE) AS MNTH_OF_CURRENT_MONTH;
SELECT DAY(DATE('2023-02-21')) AS DAY_OF_CURRENT_MONTH;

CREATE TABLE AMIR(
ID INT,
NAME VARCHAR,
DATE STRING,
DATE2 VARCHAR (20)
);

DELETE FROM AMIR;

INSERT INTO AMIR VALUES(1,'A', '2022-02-21', '2023-02-21');
INSERT INTO AMIR VALUES(2,'B', '2022-02-22', '2023-02-22');
INSERT INTO AMIR VALUES(3,'C', '2022-02-23', '2023-02-23');

SELECT * FROM AMIR;

SELECT DAY(DATE(DATE)) FROM AMIR;
SELECT DAY(DATE(DATE2)) FROM AMIR;

SELECT CURRENT_TIMESTAMP();
select day(current_timestamp() ) ,
  hour( current_timestamp() ) ,
  second(current_timestamp()) ,
  minute(current_timestamp()) ,
  month(current_timestamp());
