USE DEMODATABASE;

-- WHERE TO USE DATE_TRUNC AND EXTRACT --

SELECT DATE_TRUNC('YEAR', CURRENT_DATE) AS CURRENT_YEAR; -- IF DATA PROVIDED BY THE CLIENT IS OF MORE THAN 1 YEAR
SELECT YEAR(CURRENT_DATE) AS CURRENT_YEAR; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR
SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS CURRENT_YEAR; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR

SELECT DATE_TRUNC('QUARTER', CURRENT_DATE) AS CURRENT_QUARTER;
SELECT QUARTER(CURRENT_DATE) AS CURRENT_QUARTER_NO;
SELECT EXTRACT(QUARTER FROM CURRENT_DATE) AS CURRENT_QUARTER_NO;

SELECT DATE_TRUNC('MONTH', CURRENT_DATE) AS CURRENT_MONTH; -- IF DATA PROVIDED BY THE CLIENT IS OF MORE THAN 1 YEAR
SELECT MONTH(current_DATE) AS CURRENT_MONTH_NO; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS CURRENT_MONTH; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR

SELECT DATE_TRUNC('WEEK', CURRENT_DATE) AS CURRENT_WEEK_START_DATE; -- IF DATA PROVIDED BY THE CLIENT IS OF MORE THAN 1 YEAR
SELECT WEEK(CURRENT_DATE) AS WEEK_NO_FROM_THE_START_OF_THE_MONTH; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR
SELECT EXTRACT(WEEK FROM CURRENT_DATE) AS CURRENT_WEEK; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR

SELECT DATE_TRUNC('DAY', CURRENT_DATE) AS CURRENT_DAY; -- IF DATA PROVIDED BY THE CLIENT IS OF MORE THAN 1 YEAR
SELECT DAY(CURRENT_DATE) AS CURRENT_DAY_NO; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR
SELECT EXTRACT(DAY FROM CURRENT_DATE) AS CURRENT_DAY; -- IF DATA PROVIDED BY CLIENT IS OF 1 YEAR

---------------------------------------------------------------------------------------------------------------------

-- HOW TO CONVERT DATE GIVEN AS A STRING OR VARCHAR BY USNG DATE/TO_DATE --

SELECT DATE_TRUNC('WEEK', DATE('2023-02-21')) AS CURRENT_WEEK_START_DATE_WITH_MONTH_AND_YEAR;
SELECT DATE_TRUNC('WEEK', TO_DATE('2023-02-21')) AS CURRENT_WEEK_START_DATE_WITH_MONTH_AND_YEAR;
SELECT WEEK (DATE('2023-02-21')) AS CURRENT_WEEK_NO_FROM_THE_START_OF_THE_YEAR ;

SELECT DATE_TRUNC('DAY', TO_DATE('2023-02-19')) AS CURRENT_DAY_WITH_MONTH_AND_YEAR;
SELECT DATE_TRUNC('DAY', DATE('2023-02-19')) AS CURRENT_DAY_WITH_MONTH_AND_YEAR;
SELECT DAY(DATE('2023-02-21')) AS CURRENT_DAY_ONLY ;
                                                                   
-----------------------------------------------------------------------------------------------------------------------------------------------------------

-- TO CONVERT THE DATE ACCORDINF TO THE REQUIREMENT--

SELECT TO_CHAR(TO_DATE('1993-08-17'),'DD-MM-YYYY') AS DATE_DD_MM_YYYY; --THIS WILL BE HIGHLY USED

SELECT TO_CHAR(TO_DATE('1993-08-17'),'MM-YYYY') AS MM_YYYY;

SELECT TO_CHAR(TO_DATE('1993-08-17'),'MON-YYYY') AS MON_YYYY;

SELECT TO_CHAR(TO_DATE('1993-08-17'),'MON-YY') AS DATE_MON_YY;

SELECT TO_CHAR(TO_DATE('1993-08-17'),'DY') AS DATE_DAY;

SELECT TO_CHAR(TO_DATE('1993-08-17'),'DY-DD-MM-YYYY') AS DATE_DAY;

---------------------------------------------------------------------------------------------------------------------------------------

-- DIFFERENCE OF DATE --

select datediff('day', CURRENT_DATE, '2022-04-21'); -- OUTPUT IS -305. '-' HERE DENOTES DECREASE IN DAYS 
select datediff('day', '2022-07-23','2023-07-19'); -- OUTPUT IS 361 BECAUSE THERE IS INCREASE

select datediff('MONTH', CURRENT_DATE, '2021-06-01'); -- OUTPUT IS -20. '-' HERE DENOTES DECREASE IN MONTHS
select datediff('MONTH', '2021-06-01', CURRENT_DATE); -- OUTPUT IS 20. BECAUSE THERE IS INCREASE IN MONTHS

select datediff('WEEK', CURRENT_DATE, '2021-06-01'); -- OUTPUT IS -20. '-' HERE DENOTES DECREASE IN MONTHS
select datediff('WEEK', '2021-06-01', CURRENT_DATE); -- OUTPUT IS 20. BECAUSE THERE IS INCREASE IN MONTHS

select datediff('YEAR', CURRENT_DATE, '2021-06-01');
select datediff('YEAR', '2021-06-01',CURRENT_DATE);

-----------------------------------------------------------------------------------------------------------------------------------------

CREATE TABLE AMIR(
ID INT,
NAME VARCHAR,
DATE STRING,
DATE2 VARCHAR (20)
);

DELETE FROM AMIR;

INSERT INTO AMIR VALUES(1,'A', '2022-02-21', '2023-02-21');
INSERT INTO AMIR VALUES(2,'B', '2022-02-22', '2023-02-22');
INSERT INTO AMIR VALUES(3,'C', '2022-02-23', '2023-02-23');

SELECT * FROM AMIR;

SELECT DAY(DATE(DATE)) FROM AMIR;
SELECT DAY(DATE(DATE2)) FROM AMIR;

-------------------------------------------------------------------------------------------------------------------------------------------

SELECT CURRENT_TIMESTAMP();
select day(current_timestamp() ) ,
  hour( current_timestamp() ) ,
  second(current_timestamp()) ,
  minute(current_timestamp()) ,
  month(current_timestamp());

-- GET LAST DAY OF current MONTH
select last_day(current_date) as last_day_curr_month;

-- GET LAST DAY OF PREVIOUS MONTH
SELECT LAST_DAY(CURRENT_DATE - INTERVAL '1 MONTH') AS LAST_DAY_PREV_MNTH;

SELECT LAST_DAY(CURRENT_DATE - INTERVAL '2 MONTH') + INTERVAL '1 DAY' AS FIRST_DAY;

SELECT QUARTER(CURRENT_DATE) AS QTR;

SELECT LAST_DAY(DATE('2023-02-21'));

SELECT LAST_DAY(DATE('2023-02-21') - INTERVAL '1 MONTH')AS LAST_DAY_OF_PREVIOUS_MONTH ; --LAST DAY OF THE PREVIOUS MONTH
SELECT LAST_DAY(DATE('2023-02-21') - INTERVAL '3 MONTH')AS LAST_DAY_OF_3_MONTHS_BACK ; --LAST DAY OF 3 MONTHS BACK

SELECT DAY(DATE('2023-02-21') - INTERVAL '1 DAY') AS PREVIOUS_DAY; -- PREVIOUS DAY
SELECT DAY(DATE('2023-02-21') - INTERVAL '5 DAY') AS FIVE_DAY_BACK; --LINE 69,70,71 WILL ONLY GIVE THE DAY
SELECT DAY(DATE('2023-02-21') - INTERVAL '10 DAY') AS TEN_DAY_BACK;

SELECT DATE(DATE('2023-02-21') - INTERVAL '1 DAY') AS ONE_DAY_BACK_DATE; -- THIS WILL GIVE THE ENITRE DATE 1 DAYS BACK
SELECT DATE(DATE('2023-02-21') - INTERVAL '10 DAY') AS TEN_DAY_BACK_DATE; -- THIS WILL GIVE THE ENITRE DATE 10 DAYS BACK
SELECT DATE(DATE('2023-02-21') - INTERVAL '15 DAY') AS FIFTEEN_DAY_BACK_DATE;
SELECT DATE(DATE('2023-02-21') - INTERVAL '0.5 MONTH') AS TEN_DAY_BACK_DATE; -- MONTH IN DECIMAL DOESN'T WORK HERE, SO GIVE MONTH IN WHOLE NUMBER
SELECT DATE(DATE('2023-02-21') - INTERVAL '20 DAY') AS TWENTY_DAY_BACK_DATE; -- THIS WILL GIVE THE ENITRE DATE 20 DAYS BACK

SELECT DATE(DATE('2023-02-21') - INTERVAL '1 WEEK') AS ONE_WEEK_BACK_DATE;
SELECT DATE(DATE('2023-02-21') - INTERVAL '2 WEEK') AS TWO_WEEK_BACK_DATE;
SELECT DATE(DATE('2023-02-21') - INTERVAL '4 WEEK') AS TWO_WEEK_BACK_DATE;

SELECT DATE_TRUNC('YEAR', CURRENT_DATE) AS CURRENT_YEAR;
SELECT EXTRACT(YEAR FROM CURRENT_DATE) AS CURRENT_YEAR;

SELECT DATE_TRUNC('MONTH', CURRENT_DATE) AS CURRENT_MONTH;
SELECT EXTRACT(MONTH FROM CURRENT_DATE) AS CURRENT_MONTH;


SELECT EXTRACT(WEEK FROM CURRENT_DATE) AS CURRENT_WEEK;

SELECT DATE_TRUNC('DAY', CURRENT_DATE) AS CURRENT_DAY;
SELECT EXTRACT(DAY FROM CURRENT_DATE) AS CURRENT_DAY;

SELECT MONTHNAME('2022-02-23') FROM AMIR;-- TO GET THE NAME OF THE MONTH FROM THE GIVEN DATE

SELECT MONTHNAME(DATE(DATE2)) FROM AMIR;-- TO CONVERT INTO DATE FORMAT FROM VARCHAR DATATYPE AND TO GET THE NAME OF THE MONTH FROM THE GIVEN DATE
