USE DATABASE DEMODATABASE;

CREATE OR REPLACE TABLE AM_OWNER
(
   OwnerID INTEGER NOT NULL PRIMARY KEY ,
   Name VARCHAR2(20),
   Surname STRING,
   StreetAddress VARCHAR2(50),
   City STRING,
   State CHAR(4),
   StateFull STRING,
   ZipCode INTEGER
);


CREATE OR REPLACE TABLE AM_PETS
(
  PetID VARCHAR(10) NOT NULL PRIMARY KEY,
  Name VARCHAR (20),
  Kind STRING,
  Gender CHAR (7),
  Age INTEGER,
  OwnerID INTEGER NOT NULL REFERENCES AM_OWNER
  );


DESC TABLE AM_OWNER;
DESC TABLE AM_PETS;


SELECT * FROM AM_OWNER; -- 89 ROWS
SELECT * FROM AM_PETS;-- 100 ROWS

-- NEED THE NAME OF OWNER & THEIR DOGS NAME ALONG WITH THEIR AGE

SELECT O.OWNERID, O.NAME AS OWNER_NAME, P.NAME AS PET_NAME, AGE AS PET_AGE
FROM AM_OWNER AS O INNER JOIN AM_PETS AS P
ON O.OWNERID = P.OWNERID;

---- NEED THE NAME OF OWNER & THEIR DOGS NAME ALONG WITH THEIR AGE  ---- INNER JOIN 

CREATE OR REPLACE TABLE AM_PET_OWNER_MX AS
SELECT O.*, PETID, P.NAME AS PET_NAME, KIND, GENDER, AGE
FROM AM_OWNER AS O INNER JOIN AM_PETS AS P
ON O.OWNERID = P.OWNERID;

SELECT * FROM AM_PET_OWNER_MX;

--NEED THE NAME OF ALL THE OWNERS IRRESPECTIVE WETHER OR NOT THEY ARE HAVING PETS 


SELECT COUNT(*) FROM AM_PETS;
SELECT COUNT(*) FROM AM_OWNER;

CREATE OR REPLACE TABLE AM_PET_OWNER_OWNERSHIP AS 
SELECT P.*,O.NAME AS OWNER_NAME, CITY, STATE, ZIPCODE
FROM AM_PETS AS P LEFT OUTER JOIN AM_OWNER AS O
ON P.OWNERID = O.OWNERID;

SELECT * FROM AM_PET_OWNER_OWNERSHIP;










