DROP DATABASE IF EXISTS JOINS;
CREATE DATABASE JOINS;
USE JOINS;

DROP TABLE AM_STUDENT;

CREATE OR REPLACE TABLE AM_STUDENT(
STUDENT_ID INT NOT NULL,
NAME VARCHAR (20),
COURSE_ID INT, 
DURATION INT
);

INSERT INTO AM_STUDENT VALUES(1,'Adam',1,3);
INSERT INTO AM_STUDENT VALUES(2,'Peter',2,4);
INSERT INTO AM_STUDENT VALUES(1,'Adam',2,4);
INSERT INTO AM_STUDENT VALUES(3,'Brian',3,2);
INSERT INTO AM_STUDENT VALUES(2,'shane',3,5);

SELECT * FROM AM_STUDENT;

SELECT s1.student_id, s1.name
FROM AM_STUDENT AS s1, AM_STUDENT s2
WHERE s1.student_id=s2.student_id
AND s1.course_id<>s2.course_id;








